name       : swaybg
version    : 1.2.0
release    : 4
source     :
    - https://github.com/swaywm/swaybg/archive/refs/tags/v1.2.0.tar.gz : cfeab55b983da24352407279556c035b495890422578812d9a9c0bba1dc3ce75
license    : MIT
homepage   : https://github.com/swaywm/swaybg
component  : desktop
summary    : Wallpaper utility for Wayland compositors
description: |
    Wallpaper utility for Wayland compositors
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(scdoc)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
