name       : swaybg
version    : '1.1'
release    : 2
source     :
    - https://github.com/swaywm/swaybg/archive/refs/tags/v1.1.tar.gz : 958f425310514ae2aae064595c3e7efba2187b0d2947136c49188558fdb367b1
license    : MIT
homepage   : https://github.com/swaywm/swaybg
component  : desktop
summary    : Wallpaper utility for Wayland compositors
description: |
    Wallpaper utility for Wayland compositors
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(scdoc)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
